let font = "14px \"Helvetica Neue\",Helvetica,\"PingFang SC\",\"Microsoft YaHei\"";
let blodfont = "bold 14px \"Helvetica Neue\",Helvetica,\"PingFang SC\",\"Microsoft YaHei\"";

export default {
    "themeName": "wisTable",
    "cellPadding": 16,
    "halign": 'left',
    "gridLinesV": true,
    "gridLinesHColor": 'rgb(232, 232, 232)',
    "gridLinesVColor": 'rgb(232, 232, 232)',
    "fixedLinesHColor": 'rgb(232, 232, 232)', 
    "fixedLinesVColor": 'rgb(232, 232, 232)', 
    "font": font,
    "foregroundSelectionFont": font,
    "columnHeaderHalign": 'left',
    "columnHeaderColor": "rgb(25, 25, 25)",
    "columnHeaderForegroundSelectionColor": "rgba(46,140,240,1)",
    "columnHeaderBackgroundSelectionColor": "rgb(234,243,253)",
    "columnHeaderBackgroundColor": "rgb(250, 250, 250)",
    "columnHeaderForegroundSelectionFont": blodfont,
    "columnHeaderFont": blodfont,
    "rowHeaderFont": font,
    "rowHeaderCheckboxes":true,
    "rowHeaderNumbers":true,
    "rowHeaderForegroundSelectionFont": font,
    "rowHeaderBackgroundColor": "transparent",
    "rowHeaderColor": "rgb(25, 25, 25)",
    "rowHeaderBackgroundSelectionColor": "rgb(234,243,253)",
    "rowHeaderForegroundSelectionColor": "rgb(25, 25, 25)",
    "defaultRowHeight": 50,
    "minimumColumnWidth": 60,
    "fixedLinesHWidth": 1,
    "fixedLinesVWidth": 1,
    "lineColor": "rgb(210,210,210)",
    "backgroundColor2": "rgb(0,0,0)",
    "color": "rgb(25, 25, 25)",
    "fontFamily": font,
    "backgroundColor": "rgb(255, 255, 255)",
    "backgroundSelectionColor": "transparent",
    "foregroundSelectionColor": "rgb(25, 25, 25)",
    "fixedColumnBackgroundSelectionColor": "rgb(232, 232, 232)",
    "selectionRegionOutlineColor":"rgba(46,140,240,0.5)",
    "selectionRegionOverlayColor": "rgba(46,140,240,0.1)",
};
